### ISSUE TITLE
Example code doen't work

### ISSUE THREAD

**Issue by wizzardx** [duyixian1234/html_dsl#1]
This line doesn't work:

`from html_dsl.elements import BaseHtmlElement, HTML, BODY, H1, P, DIV, SPAN
`

html_dsl/elements.py doeosn't include identifiers HTML, BODY, H1, etc, so I get this error:

```
$ python test.py
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from html_dsl.elements import BaseHtmlElement, HTML, BODY, H1, P, DIV, SPAN
ImportError: cannot import name 'HTML' from 'html_dsl.elements' (/tmp/x/venv/lib/python3.8/site-packages/html_dsl/elements.py)
```

Instead, I need to use this import line for the example to work:

`from html_dsl.common import HTML, BODY, H1, P, SPAN, DIV
`

pip installed this wheel on my testing virtualenv, which has the problem:

```
$ pip install html_dsl
Collecting html_dsl
  Downloading html_dsl-0.4.0-py3-none-any.whl (3.5 kB)
Installing collected packages: html-dsl
Successfully installed html-dsl-0.4.0

```
I'm running on Ubuntu Focal (20.04), with Python 3.8.5

**Comment by duyixian1234** [comment]
I'm sorry which I have refactored this project a much but not updated the README. I'd like to fix it soon.
